services:
  db:
    container_name: db
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./databases:/var/lib/postgresql/data/"
    restart: always

  app:
    build: .
    container_name: rest_care
    image: rest_care-app
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - "./src:/usr/src/app/src"
      - "/usr/src/app/node_modules/"

  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - "./redis_data:/data/"
